### ISSUE TITLE
Version 0.02, many times the left area, not able to return directly to the previous page

### ISSUE THREAD

**Issue by XuanNui** [zsviczian/excalibrain#14] opened 2022-05-06 05:07 UTC
Version 0.02, many times the left area, not able to return directly to the previous page (only in the left area of the operation to return)
![upload 00_00_00-00_00_30](https://user-images.githubusercontent.com/104402409/167070520-9c56ac85-c8da-49a9-a89f-beb4de4a47f5.gif)

**Comment by zsviczian** [comment] 2022-05-06 05:15
Thanks. I was able to reproduce.

**Comment by zsviczian** [comment] 2022-05-06 14:16
I think I found the root cause. Will be resolved in 0.0.3

**Comment by zsviczian** [comment] 2022-05-06 14:36
I'll see if I can solve this. In the meantime, I recommend installing the Pane Relife plugin which solved this problem for me.

**Comment by XuanNui** [comment] 2022-05-07 02:37
tks，the problem is solved。

**Closed** 2022-05-07 05:20 UTC
Labels: good first issue
